name: AdminChat
main: tc.oc.adminchat.AdminChat
version: ${project.version}
author: Overcast Network

commands:
  a:
    description: Use admin chat
    usage: /<command> <msg>

permissions:
  chat.admin:
    description: Allows sending and recieving of admin chat messages
    default: op
    children:
      chat.admin.send: true
      chat.admin.recieve: true
  chat.admin.send:
    description: Allows sending of admin chat messages
    default: op
  chat.admin.recieve:
    description: Allows recieving of admin chat messages
    default: op
